// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCChdSomAtlK_FOMCwaXvBUC5xbfgIfvjo',
    appId: '1:259318464607:web:36f9b96057aa5a96909bea',
    messagingSenderId: '259318464607',
    projectId: 'scribesync-f96ec',
    authDomain: 'scribesync-f96ec.firebaseapp.com',
    storageBucket: 'scribesync-f96ec.firebasestorage.app',
    measurementId: 'G-P9RHDQ6FYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoEfMwhovLFPkrPSclqE2hHI_1HstqA0g',
    appId: '1:259318464607:android:66daf8caa2ccdfe8909bea',
    messagingSenderId: '259318464607',
    projectId: 'scribesync-f96ec',
    storageBucket: 'scribesync-f96ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLiETZ-zLKvCzlE5mwjt7FOdU1YMZdMY',
    appId: '1:259318464607:ios:fa082968b62eecb7909bea',
    messagingSenderId: '259318464607',
    projectId: 'scribesync-f96ec',
    storageBucket: 'scribesync-f96ec.firebasestorage.app',
    iosBundleId: 'com.example.scribesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZLiETZ-zLKvCzlE5mwjt7FOdU1YMZdMY',
    appId: '1:259318464607:ios:fa082968b62eecb7909bea',
    messagingSenderId: '259318464607',
    projectId: 'scribesync-f96ec',
    storageBucket: 'scribesync-f96ec.firebasestorage.app',
    iosBundleId: 'com.example.scribesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCChdSomAtlK_FOMCwaXvBUC5xbfgIfvjo',
    appId: '1:259318464607:web:345f09d7141b49b4909bea',
    messagingSenderId: '259318464607',
    projectId: 'scribesync-f96ec',
    authDomain: 'scribesync-f96ec.firebaseapp.com',
    storageBucket: 'scribesync-f96ec.firebasestorage.app',
    measurementId: 'G-6W4F8ZE3NK',
  );
}
